# Define goal (what the client sends to the control node)
string command # servo, close_gripper, open_gripper, insert, raise
---
# Define result (what the node returns upon completion)
bool success  # true if the action succeeded
---
# Define feedback (optional, sent during action execution)
string status
